---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/cp -R $TRAVIS_BUILD_DIR/* $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
